name: example-environment
channels:
  - conda-forge
  - weiyan
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - partd
  - bokeh
  - libsndfile
  - dask
  - pip
  - pip:
    - scikits.audiolab
